# Generated by Django 6.0.6 on 2026-06-26 20:04

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('organization', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('Recruitment', 'Recruitment'), ('Networking', 'Networking'), ('Industry Query', 'Industry Query')], max_length=100)),
                ('message', api.models.EncryptedTextField(help_text='This field is encrypted at rest in the database.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationAndCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(help_text='e.g., Chartered Accountant or B.Com', max_length=150)),
                ('institution', models.CharField(help_text='e.g., ICAI or DDU Gorakhpur University', max_length=150)),
                ('year', models.CharField(help_text='e.g., Qualified May 2026 or 2019', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Used to manually order education entries.')),
            ],
            options={
                'verbose_name': 'Education and Credential',
                'verbose_name_plural': 'Education and Credentials',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExecutiveProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='CA Priyam Gupta', max_length=100)),
                ('designation', models.CharField(default='Chartered Accountant (ICAI) & CS Professional (G1)', max_length=200)),
                ('bio', models.TextField(help_text='A 150-word objective-driven statement focusing on transition to corporate roles.')),
                ('profile_image_url', models.CharField(blank=True, help_text='URL or path to the professional headshot.', max_length=500)),
                ('metric1_value', models.CharField(default='80+', help_text='e.g., 80+', max_length=50)),
                ('metric1_label', models.CharField(default='Statutory & Tax Audits Executed', max_length=100)),
                ('metric2_value', models.CharField(default='3+', help_text='e.g., 3+', max_length=50)),
                ('metric2_label', models.CharField(default='Years Intensive Corporate Experience', max_length=100)),
                ('metric3_value', models.CharField(default='Dual', help_text='e.g., Dual', max_length=50)),
                ('metric3_label', models.CharField(default='Professional Focus (CA & CS G1)', max_length=100)),
            ],
            options={
                'verbose_name': 'Executive Profile',
                'verbose_name_plural': 'Executive Profiles',
            },
        ),
        migrations.CreateModel(
            name='ExperienceTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(help_text='e.g., Executive or Article Assistant', max_length=150)),
                ('company_name', models.CharField(help_text='e.g., Himanshu Tibrewal & Associates', max_length=150)),
                ('period', models.CharField(help_text='e.g., Sep 2025 – Oct 2025', max_length=100)),
                ('location', models.CharField(help_text='e.g., Gorakhpur', max_length=100)),
                ('key_responsibilities', models.JSONField(help_text='A list (JSON array) of bullet points representing responsibilities.')),
                ('is_executive', models.BooleanField(default=False, help_text='Check if this is an Executive role vs. Article Assistant.')),
                ('order', models.IntegerField(default=0, help_text='Used to manually order timeline entries.')),
            ],
            options={
                'verbose_name': 'Experience Timeline',
                'verbose_name_plural': 'Experience Timelines',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Auditing & Assurance', 'Auditing & Assurance'), ('Taxation & Compliance', 'Taxation & Compliance'), ('Financial Analysis', 'Financial Analysis'), ('Tools & Software', 'Tools & Software')], max_length=100)),
                ('skill_name', models.CharField(help_text='e.g., Statutory Audit or Tally Prime', max_length=100)),
            ],
            options={
                'verbose_name': 'Professional Skill',
                'verbose_name_plural': 'Professional Skills',
                'ordering': ['category', 'skill_name'],
            },
        ),
    ]
